
using System.Collections;
using System.Collections.Concurrent;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using DynTypeSerializer;

namespace DynTypeNetwork;

public enum MessageDirection : byte
{
    None,
    Request,
    Response
}

public class NetworkMessage
{
    public int SenderId { get; set; }
    public int TargetId { get; set; }
    public MessageType MessageType { get; set; }

    /// <summary>Set by the API users</summary>
    public ushort CustomMessageType { get; set; }
    public long Timestamp { get; set; } = DateTime.UtcNow.Ticks;

    /// <summary>
    /// Unique identifier for this message (can be generated by sender).
    /// </summary>
    public ushort MessageId { get; set; } = 0;


    // Internal members: not visible outside the assembly
    internal byte[] PayloadBytes { get; set; } = [];
    internal int PayloadLength => PayloadBytes.Length;
}

public enum MessageType
{
    ServerShutdown,
    Handshake,
    ClientConnected,
    ClientDisconnected,
    Request,
    Response,

    Custom,

    Update,
}

public static class Network
{
    // TODO remove from here
    private static readonly int HardcodedSenderId = 1;

    public static byte[] SendMessage<T>(int targetId, MessageType messageType, T data)
    {
        var msg = new NetworkMessage
        {
            SenderId = HardcodedSenderId,
            TargetId = targetId,
            MessageType = messageType,
            Timestamp = DateTime.UtcNow.Ticks
        };
        return Pack(msg, data);
    }

    internal static byte[] Pack(NetworkMessage msg)
    {
        int payloadLength = msg.PayloadBytes?.Length ?? 0;

        msg.Timestamp = DateTime.UtcNow.Ticks;

        var buffer = new List<byte>();
        buffer.AddRange(BitConverter.GetBytes(msg.SenderId));           // 4 bytes
        buffer.AddRange(BitConverter.GetBytes(msg.TargetId));           // 4 bytes
        buffer.AddRange(BitConverter.GetBytes((short)msg.MessageType)); // 2 bytes
        buffer.AddRange(BitConverter.GetBytes(msg.MessageId));          // 2 bytes
        buffer.AddRange(BitConverter.GetBytes(msg.Timestamp));          // 8 bytes
        buffer.AddRange(BitConverter.GetBytes(payloadLength));          // 4 bytes
        if (payloadLength > 0) buffer.AddRange(msg.PayloadBytes!);      // payload
        return buffer.ToArray();
    }

    internal static byte[] Pack<T>(NetworkMessage msg, T obj)
    {
        msg.PayloadBytes = Encoding.UTF8.GetBytes(Serializer.Serialize(obj));
        return Pack(msg);
    }

    public static T? Unpack<T>(byte[] data)
    {
        // Fixed offsets:
        // SenderId (4) + TargetId (4) + MessageType (2) + MessageID (2) + Timestamp (8)
        int offset = 4 + 4 + 2 + 2 + 8;

        // Read payload length
        int payloadLength = BitConverter.ToInt32(data, offset);
        offset += 4;

        // Extract payload
        byte[] payload = payloadLength > 0 ? data[offset..(offset + payloadLength)] : [];
        if (payload.Length == 0) return default;

        // Deserialize
        var json = Encoding.UTF8.GetString(payload);
        return Serializer.Deserialize<T>(json);
    }

    public static void Unpack(byte[] data, out NetworkMessage msg)
    {
        int offset = 0;

        int senderId = BitConverter.ToInt32(data, offset); offset += 4;
        int targetId = BitConverter.ToInt32(data, offset); offset += 4;
        MessageType messageType = (MessageType)BitConverter.ToInt16(data, offset); offset += 2;
        ushort messageId = BitConverter.ToUInt16(data, offset); offset += 2;
        long timestamp = BitConverter.ToInt64(data, offset); offset += 8;
        int payloadLength = BitConverter.ToInt32(data, offset); offset += 4;

        msg = new NetworkMessage
        {
            SenderId = senderId,
            TargetId = targetId,
            MessageType = messageType,
            MessageId = messageId,
            Timestamp = timestamp,
            PayloadBytes = payloadLength > 0 ? data[offset..(offset + payloadLength)] : []
        };
    }
    public static MessageType ReadMessageType(byte[] data)
    {
        if (data.Length < 4 + 4 + 2) // SenderId + TargetId + MessageType
            throw new ArgumentException("Packet too short to contain a valid header.", nameof(data));

        // MessageType offset: after SenderId (4) + TargetId (4) = offset 8
        int offset = 4 + 4;
        return (MessageType)BitConverter.ToInt16(data, offset);
    }
    public static NetworkMessage ReadMessage(byte[] data, bool includeData = false)
    {
        // Minimum length: SenderId (4) + TargetId (4) + MessageType (2) + Timestamp (8) + PayloadLength (4)
        if (data.Length < 4 + 4 + 2 + 8 + 4)
            throw new ArgumentException("Packet too short to contain a valid header.", nameof(data));

        int offset = 0;

        int senderId = BitConverter.ToInt32(data, offset); offset += 4;
        int targetId = BitConverter.ToInt32(data, offset); offset += 4;
        MessageType messageType = (MessageType)BitConverter.ToInt16(data, offset); offset += 2;
        ushort messageId = BitConverter.ToUInt16(data, offset); offset += 2;
        long timestamp = BitConverter.ToInt64(data, offset); offset += 8;
        int payloadLength = BitConverter.ToInt32(data, offset); offset += 4;

        // Return the NetworkMessage with only header info populated
        return new NetworkMessage
        {
            SenderId = senderId,
            TargetId = targetId,
            MessageType = messageType,
            MessageId = messageId,
            Timestamp = timestamp,
            PayloadBytes = includeData && payloadLength > 0
                ? data[offset..(offset + payloadLength)]
                : []
        };
    }
}